### ISSUE TITLE
Error when attempting to run the script on an existing 1.12.x world

### ISSUE THREAD

**Issue by TheMCNerd2017** [BranislavBajuzik/1.12-to-1.13#1]
![image](https://user-images.githubusercontent.com/25375242/34912104-f3211364-f8a5-11e7-9ad7-162d06c003d0.png)

This complicated error message comes up whenever I attempt to use the converter on a 1.12.x world. I have no idea why this is happening, as I did not run the converter on the world before, nor did I open the world in a 1.13 snapshot.

**Comment by TheMCNerd2017** [comment]
Yeah, I knew something might have been wrong when the error kept happening. Also, I have Python 2 installed alongside Python 3, so how should I go about making the script run with Python 2?

**Comment by BranislavBajuzik** [comment]
Open the folder with the `.py` file in the standard file explorer, click into the path (It should have `ThisPC > LocalDisk(C:) > Users > Nicholas > AppData > Roaming > .minecraft > saves > Minecraft Brawl 1.13.x` in there), type `cmd` and press enter. Now you have a terminal.
Next up find where your Python 2 installation is (it should be in standard program files) and copy the path to the `python.exe` file (for me it's `"D:\ProgramFiles\CPython2.7.14\python.exe"`. You don't need the `"` unless there is space in your path.).

Now type in the console the path to the python exe, space, and then the program name and press enter (for me it's `"D:\ProgramFiles\CPython2.7.14\python.exe" 1_12to1_13.py`)
